---
title: "Flu-Edinburgh colaboration"
author: "Oscar de León"
date: "May 20, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
# Load used packages
library(package = "lubridate")
library(package = "tidyverse")


# Define study metadata
study_years <- 2010:2016
study_sites <- c("H-Cuilapa", "H-Xela")


# Setup knitting
knitr::opts_knit$set(root.dir = "..")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```



```{r load-data}
# Run data preparation scripts
source(file = "scripts/get-server-data.R")
source(file = "scripts/get-population-data.R")
```



```{r clean-data}
# Catchment
catchment <- catchment %>%
  # Fix casing
  mutate_at(
    vars(department, municipality),
    funs(
      gsub(
        "(^| )([a-z])", "\\1\\U\\2",
        tolower(iconv(., to = "ASCII//TRANSLIT")),
        perl = TRUE
      )
    )
  ) %>%
  # Fix typos
  mutate(
    municipality = recode(
      municipality,
      "Santa Cruz Naranajo" = "Santa Cruz Naranjo",
      "Concepcion Chiquirichap" = "Concepcion Chiquirichapa",
      "San Martin Sacatepeque" = "San Martin Sacatepequez"
    )
  )


# Surveillance data
study_respi <- study_respi %>%
  # Fix casing
  mutate_at(
    vars(case_department, case_municipality),
    funs(
      gsub(
        "(^| )([a-z])", "\\1\\U\\2",
        tolower(iconv(., to = "ASCII//TRANSLIT")),
        perl = TRUE
      )
    )
  ) %>%
  # Label variables
  mutate(
    # Site department
    site_department = recode(
      site_department,
      "QU" = "Quetzaltenango",
      "SR" = "Santa Rosa"
    ),
    # Location for population
    site_location = recode(
      site_name,
      "H-Cuilapa" = "Santa Rosa",
      "H-Xela" = "Quetzaltenango",
      "CS-NSR" = "Nueva Santa Rosa"
    ),
    # Fix catchment municipalities
    case_municipality = recode(
      case_municipality,
      "Colomba Costa Cuca" = "Colomba",
      "Ostuncalco" = "San Juan Ostuncalco",
      "San Miguel Signila" = "San Miguel Siguila",
      .default = case_municipality
    ),
    # Label age groups
    age_group = case_when(
      age_years == 0 & age_months == 0 & age_days < 28 ~ "0-27 days",
      age_years == 0 & age_months < 3 ~ "28 days-<3 month",
      age_years == 0 & age_months < 6 ~ "3-5 months",
      age_years == 0 & age_months < 9 ~ "6-8 months",
      age_years == 0 & age_months < 12 ~ "9-11 months",
      (age_years == 0 & age_months == 12) |
        between(age_years, 1, 1) ~ "12-23 months",
      between(age_years, 2, 2) ~ "24-35 months",
      between(age_years, 3, 4) ~ "36-59 months",
      TRUE ~ NA_character_
    ),
    age_group = factor(age_group, levels = labels_age_groups, ordered = TRUE)
  ) %>%
  # Label respiratory indications
  left_join(
    select(
      labels_respi, respiratory_indications = value, respiratory_indication_label = text
    )
  ) %>%
  # Only keep cases under 5 yoa
  filter(
    !is.na(age_group),             # Defined age groups
    year %in% study_years          # During the study period
  )


# Population data
catchment_population <- population %>%
  # Tag as catchment area
  left_join(catchment) %>%
  filter(catchment == 1) %>%
  # Tag locations for hospitals
  mutate(location = department) %>%
  # Tag locations for NSR
  bind_rows(
    mutate(
      filter(., municipality == "Nueva Santa Rosa"),
      location = municipality
    )
  ) %>%
  # Summarize population for each location, year and age group
  group_by(location, age_group, year) %>%
  summarize(population = sum(population)) %>%
  ungroup()
```



```{r assign-case-definitions}
# Function to check symptoms
presents <- function(var){
  if_else(
    condition = var == 1 & !is.na(var),
    true = 1L,
    false = 0L
  )
}

# Function to check lab results
result <- function(var){
  if_else(
    condition = var %in% c(0, 1),
    true = presents(var),
    false = NA_integer_
  )
}

#------------------------------------------------------------------------------*
# Study sites considered pasive hospital based
#------------------------------------------------------------------------------*
# Definitions stated when testing each row
#------------------------------------------------------------------------------*
alri_cases <- study_respi %>%
  # Tag records with altitude
  left_join(
    rename(
      catchment, site_department = department, case_municipality = municipality
    )
  ) %>%
  filter(
    # Only records from hospitals
    site_type == "H",
    # Only records from catchment areas
    catchment == 1
  ) %>%
  # Tag records with altitude
  left_join(
    select(all_sites, site_name, altitude)
  ) %>%
  mutate(
    # Use oxygen saturation without oxygen supplementation if available
    blood_oxigen_sat = if_else(
      condition = !is.na(blood_oxigen_no_supp) &
        # Remove outliers
        blood_oxigen_no_supp > 30,
      true = blood_oxigen_no_supp,
      false = blood_oxigen_sat
    ),
    # Hypoxemia
    hypoxemia = case_when(
      # SpO2 <90% (at altitude ≤2500 m) in children aged 1-59 months
      altitude <= 2500 &
        age_years < 5 &
        (age_months >= 1 | is.na(age_months) | age_days >= 28) &
        blood_oxigen_sat < 90 ~ 1,
      # <88% for neonates (at sea level)
      altitude <= 2500 &
        age_years == 0 & age_months == 0 & age_days <= 27 &
        blood_oxigen_sat < 88 ~ 1,
      # At altitude above 2500m, SpO2 <87% in children aged 1-59 months
      altitude > 2500 &
        age_years < 5 &
        (age_months >= 1 | is.na(age_months) | age_days >= 28) &
        blood_oxigen_sat < 87 ~ 1,
      # and <85% for neonates would classify as hypoxemia.
      altitude <= 2500 &
        age_years == 0 & age_months == 0 & age_days <= 27 &
        blood_oxigen_sat < 85 ~ 1,
      # Otherwise no hypoxemia
      TRUE ~ 0
    ),
    # Use highest recorded respiratory rate
    respiratory_rate = pmax(
      respiratory_rate_chart, respiratory_rate_obs, na.rm = TRUE
    ),
    # Define tachypnea
    tachypnea = case_when(
      age_years == 0 & age_months < 2 & respiratory_rate >= 60 ~ 1,
      age_years = 0 & age_months >= 2 & respiratory_rate >= 50 ~ 1,
      (age_years >= 1 | (age_years == 0 & age_months == 12)) &
        respiratory_rate >= 40 ~ 1,
      # Otherwise no tachypnea
      TRUE ~ 0
    ),
    # Define physician diagnosis
    phys_diagnosis = presents(
      respiratory_indication_label %in% c(
        "NAC- Neumonía adquirida comunitaria",
        "Bronconeumonía",
        "Bronquiolitos",
        "Neumonía - NM"
      )
    ),
    # Danger signs
    # (cyanosis, difficulty in breastfeeding or drinking, vomiting everything,
    # convulsions, lethargy, or unconsciousness, head nodding)
    danger_signs = presents(
      presents(cyanosis_obs) | presents(difficulty_feeding) |
      presents(vomits_everything) |
      presents(convulsions_hist) | presents(convulsions_obs) |
      presents(lethargy) | presents(unconciousness) | presents(head_nodding)
    ),
    # Proxies of very severe disease (mechanical ventilation OR ICU admission)
    severe_disease_proxies = presents(
      presents(ventilation) | presents(icu_days > 0)
    ),
    # ALRI cases
    alri = presents(
      presents(
        (presents(cough) | presents(difficulty_breathing)) & presents(tachypnea)
      ) |
        phys_diagnosis
    ),
    # Hospitalised influenza associated ALRI (passive hospital based case
    # ascertainment)  all children with physician confirmed diagnosis of ALRI
    # (pneumonia or bronchiolitis) that are hospitalised or recommended
    # hospitalisation and laboratory confirmed influenza
    hosp_alri = presents(presents(alri) & presents(hospitalized)),
    # Hospitalised Influenza associated very severe ALRI (passive hospital
    # based case ascertainment): hospitalised ALRI with one danger sign OR
    # proxies for very severe disease
    hosp_alri_very_severe = presents(
      presents(hosp_alri) & (presents(danger_signs) | presents(severe_disease_proxies))
    ),
    # Hospitalised influenza-associated severe ALRI (passive hospital based
    # case ascertainment): Hospitalised ALRI cases with hypoxemia (as defined
    # below) and laboratory confirmed influenza
    hosp_alri_severe = presents(
      (presents(hosp_alri) & presents(hypoxemia)) |
        presents(hosp_alri_very_severe)
    ),
    # Influenza laboratory results
    flu_a_h1 = result(flu_a_h1),
    flu_a_h1_09pdm = result(if_else(is.na(flu_a_swa), flu_a_pdmh1, flu_a_swh1)),
    flu_a_h3 = result(flu_a_h3),
    flu_a = if_else(
      condition = !is.na(flu_a_h1) | !is.na(flu_a_h3) | !is.na(flu_a_h1_09pdm),
      true = 1L,
      false = if_else(
        condition = !is.na(flu_a),
        true = 0L,
        false = NA_integer_
      )
    ),
    flu_b = result(flu_b & !flu_a),
    flu_any = presents(flu_a | flu_b),
    not_tested = presents(is.na(flu_a))
  )

# Label lab results
label_lab_results <- tribble(
  ~assay, ~name,
  "flu_a_h1", "A(H1N1)",
  "flu_a_h1_09pdm", "A(H1N1)09pdm",
  "flu_a_h3", "A(H3N2)",
  "flu_a", "Influenza A (sub and unsub)",
  "flu_b", "Influenza B",
  "flu_any", "All influenza (subtyped and unsubtyped)"
)
```



```{r count-cases}
#------------------------------------------------------------------------------*
# Collect minimal variables for the ALRI case count
#------------------------------------------------------------------------------*
alri_minimal <- alri_cases %>%
  filter(
    # Only keep alri cases
    alri == 1,
    # Only keep hospitalized cases
    hospitalized == 1
  ) %>%
  group_by(site_name, year) %>%
  mutate(
    n = n(),
    not_tested = sum(not_tested)
  ) %>%
  ungroup() %>%
  select(
    site_name, year, n, not_tested, age_group,
    hosp_alri, hosp_alri_severe, hosp_alri_very_severe,
    flu_a_h1, flu_a_h1_09pdm, flu_a_h3, flu_a, flu_b, flu_any
  )


#------------------------------------------------------------------------------*
# Complete age groups and all combinations of data levels
#------------------------------------------------------------------------------*
alri_all_groups <- alri_minimal %>%
  # Gather alri by case definition
  gather(
    key = case_type, value = value,
    hosp_alri, hosp_alri_severe, hosp_alri_very_severe
  ) %>%
  filter(value == 1) %>%
  select(-value) %>%
  # Add summary age groups
  bind_rows(
    # 0-11 months
    mutate(
      filter(., age_group < c("0-11 months")),
      age_group = factor(
        "0-11 months",
        levels = levels(age_group)
      )
    ),
    # 0-59 months
    mutate(
      filter(., age_group < c("0-59 months")),
      age_group = factor(
        "0-59 months",
        levels = levels(age_group)
      )
    ),
    # 12-59 months
    mutate(
      filter(., age_group > c("0-11 months")),
      age_group = factor(
        "12-59 months",
        levels = levels(age_group)
      )
    ),
    # 24-59 months
    mutate(
      filter(., age_group > c("12-23 months")),
      age_group = factor(
        "24-59 months",
        levels = levels(age_group)
      )
    )
  ) %>%
  gather(
    key = assay, value = result,
    flu_a_h1, flu_a_h1_09pdm, flu_a_h3, flu_a, flu_b, flu_any
  ) %>%
  # Complete all combinations
  right_join(
    expand(., site_name, year, case_type, age_group, assay)
  ) %>%
  group_by(site_name, year) %>%
  mutate(
    n = first(na.omit(n)),
    not_tested = first(na.omit(not_tested))
  ) %>%
  ungroup()


#------------------------------------------------------------------------------*
# Summarize cases by site, year, case type, flu type/subtype and age
#------------------------------------------------------------------------------*
alri_summarized <- alri_all_groups %>%
  mutate(
    not_tested = paste0(
      not_tested, " of ", n,
      " (", scales::percent(not_tested / n), ")"
    )
  ) %>%
  group_by(site_name, year, not_tested, case_type, age_group, assay) %>%
  summarize(
    cases = sum(result, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate(
    text = "",
    # order results
    case_type = recode_factor(
      case_type,
      hosp_alri = "hospitalized alri",
      hosp_alri_severe = "hospitalized severe alri",
      hosp_alri_very_severe = "hospitalized very severe alri",
      .default = NA_character_,
      .ordered = TRUE
    ),
    assay = factor(
      assay,
      levels = c(
        "flu_a_h1", "flu_a_h1_09pdm", "flu_a_h3",
        "flu_a", "flu_b", "flu_any"
      ),
      ordered = TRUE
    ),
    column = factor(
      paste(case_type, assay, age_group, sep = "\n"),
      levels = paste(
        rep(
          paste(
            rep(levels(case_type), each = length(levels(assay))),
            rep(levels(assay), times = length(levels(case_type))),
            sep = "\n"
          ),
          each = length(levels(age_group))
        ),
        levels(age_group),
        sep = "\n"
      ),
      ordered = TRUE
    )
  ) %>%
  arrange(column)


# Write wide output
alri_summarized %>%
  select(-case_type, -age_group, -assay) %>%
  spread(key = column, value = cases, fill = 0) %>%
  write_csv(path = "output/hosp_alri.csv")
```

